---
title: "Getting and Cleaning Data- Project README"
---
####*Hui-yu Yang*
####*July 17 2015*

This repository was created for the project of coursera course "Getting and Cleaning Data." The dataset was downloaded from [the UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).

### The dataset includes the following files:

- **run_analysis.R**: Gets the data online and creates a dataset with the average of 79 features associated with mean or sd per subject and activity. 

- **CodeBook.Rmd**: describes the data, list of variables, and how data was processed in run_analysis.R. 

- **tidydata.txt**: output text file from run_analysis.R. 

### License:

Use of this dataset in publications must be acknowledged by referencing the following publication [1] 

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.

Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012.